#!usr/bin/python

'''
This will return a list of dictionaries of questions in this format

[{"question":___,"difficulty":___,"category":___,correct_ans":___,"wrong_ans":[__,__,__],"type":___ },]

'''
import urllib2, json

def get_questions(questions,category):
	datastuff = urllib2.urlopen(source)
	jason = datastuff.read()
	d = json.loads(jason)
	print d
	req = urllib2.Request(url)
	text_data = urllib2.urlopen(req).read()
	jason2 = json.loads(text_data)
